<?php
$src = <<<BOOKS
ALICE IN WONDERLAND
ALL OF ME
ALL OF YOU
ALL THE THINGS YOU ARE
ALONE TOGETHER
ANTICALYPSO
AS TIME GOES BY
AUTUMN LEAVES
AU PRIVAVE
BEAUTIFUL LOVE
BEWITCHED
BILLIE'S BOUNCE
BLACK ORPHEUS
BLUE MONK
BLUE MOON
BLUES MARCH
BODY AND SOUL
BRAZIL
BUT BEAUTIFUL
BUT NOT FOR ME
BYE BYE BLACKBIRD
CALIFORNIA HERE I COME
CANDY
CHILD IS BORN, A
CIPRIANA
COME RAIN OR COME SHINE
CONFIRMATION
CRY ME A RIVER
DANNY BOY
DAY BY DAY
DAYS OF WINE AND ROSES, THE
DONNA LEE
EAST OF THE SUN
EASY LIVING
EMBRACEABLE YOU
EMILY
EYES OF LOVE,THE
EVERYTHING HAPPENS TO ME
FALLING IN LOVE WITH LOVE
FIVE PENNIES, THE
FLY ME TO THE MOON
FOGGY DAY, A
FOUR
FOUR ON SIX
GENTLE RAIN, THE
GEORGIA ON MY MIND
GIANT STEPS
GIRL FROM IPANEMA, THE
GONE WITH THE WIND
GOODNIGHT SWEETHEART
GROOVIN' HIGH
HERE'S THAT RAINY DAY
HOW ABOUT YOU?
I CAN'T GET STARTED
I CAN'T GIVE YOU ANYTHING GUT LOVE
I CONCENTRATE ON YOU
I COULD WRITE A BOOK
I DIDN'T KNOW WHAT TIME IT WAS
IF I SHOULD LOSE YOU
IF I WERE A BELL
I GOT RHYTHM
I HEAR A RHAPSODY
I LEFT MY HEART IN SAN FRANCISCO
I'LL CLOSE MY EYES
I LOVE YOU
I'LL REMEMBER APRIL
IMAGINATION
I'M BEGINNING TO SEE THE LIGHT
I'M GETTIN' SENTIMENTAL OVER YOU
I'M IN THE MOOD FOR LOVE
I'M OLD FASHIONED
IMPRESSIONS
IN A MELLOW TONE
IN A SENTIMENTAL MOOD
INTER PLAY
IN THE STILL OF THE NIGHT
IN WALKED BUD
INVITATION
IN YOUR OWN SWEET WAY
I REMEMBER CLIFFORD
I REMEMBER YOU
I SHOULD CARE
ISN'T IT ROMANTIC?
ISN'T SHE LOVELY
ISRAEL
IT COULD HAPPEN TO YOU
IT DON'T MEAN A THING
IT'S ALL RIGHT WITH ME
IT'S YOU OR NO ONE
JEANNINE
JUST FRIENDS
JUST IN TIME
LAURA
LEFT ALONE
LIKE SOMEONE IN LOVE
LOVE FOR SALE
LOVE LETTERS
LOVER MAN
LULLABY OF BIRDLAND
MANBO INN
MEMORIES OF YOU
MILESTONES
MISTY
MOANIN'
MOMENT'S NOTICE
MONA LIZA
MOONGLOW
MOON RIVER
MORE
MORITAT
Mr. P. C.
MY FOOLISH HEART
MY FUNNY VALENTINE
MY IDEAL
MY LITTLE SUEDE SHOES
MY OLD FLAME
MY ONE AND ONLY LOVE
MY ROMANCE
NANCY
NARDIS
NEARNESS OF YOU, THE
NIGHT AND DAY
NIGHT HAS A THOUSAND EYES, THE
NIGHTINGALE SANG IN BERKELEY SQUARE, A
NICA'S DREAM
NOBODY ELSE BUT ME
NOW'S THE TIME
OLEO
OLD FOLKS
ON GREEN DOLPHIN STREET
ONE FOR HELEN
ONLY YOU
ORNITHOLOGY
OUR DELIGHT
OUR LOVE IS HERE TO STAY
OUT OF NOWHERE
OVER THE RAINBOW
PERDIDO
PLUM
POLKA DOTS AND MOON BEAMS
RECARDO BOSSA NOVA
RECORDA-ME
ROAD SONG
'ROUND MIDNIGHT
SAMBA DE ORFEU
SATIN DOLL
SCRAPPLE FROM THE APPLE
SECRET LOVE
SEPTEMBER IN THE RAIN
SEVEN STEPS TO HEAVEN
SHADOW OF YOUR SMILE, THE
SHIROI-NAMI
SKYLARK
SMOKE GETS IN YOUR EYES
SO DANCE SAMBA
SO IN LOVE
SOLAR
SOLITUDE
SOMEDAY MY PRINCE WILL COME
SO NICE
SOFTLY, AS IN A MORNING SUNRISE
SOMEONE TO WATCH OVER ME
SOPHISTICATED LADY
SPEAK LOW
STAR DUST
STAR EYES
STELLA BY STARLIGHT
STRAIGHT NO CHASER
STRANGERS IN THE NIGHT
ST. THOMAS
SUGAR
SUMMERTIME
'S WONDERFUL
TAKE THE "A" TRAIN
TANGERINE
TEA FOR TWO
TENOR MADNESS
THAT'S ALL
THERE IS NO GREATER LOVE
THERE WILL NEVER BE ANOTHER YOU
THERMO
THESE FOOLISH THINGS
TENDERLY
TOO YOUNG
TRAV'LIN' LIGHT
VERY THOUGHT OF YOU, THE
WALTS FOR DEBBY
WATCH WHAT HAPPENS
WALKIN'
WAVE
WELL YOU NEEDN'T
WHAT ARE YOU DOING FOR THE REST OF YOUR LIFE
WHAT KIND OF FOOL AM I?
WHAT'S NEW?
WHEN SUNNY GETS BLUE
WHEN YOU'RE SMILING
WHEN YOU WISH UPON A STAR
WHISPER NOT
WHO CAN I TURN TO
WILLOW WEEP FOR ME
WITH A SONG IN MY HEART
WOULD YOU DANCE WITH A STRANGER
X'MAS SONG, THE
YA GOTTA TRY
YARDBIRD SUITE
YESTERDAY'S DREAMS
YOU ARE TOO BEAUTIFUL
YOU'D BE SO NICE TO COME HOME TO
YOU AND THE NIGHT AND THE MUSIC
YOU DON'T KNOW WHAT LOVE IS
BOOKS;

$tunes = explode("\n", $src);
// echo(mysql_real_escape_string(json_encode($tunes)));

echo "INSERT INTO books_tunes(book_id, tune_id) VALUES";
$relations = [];
for ($i=1; $i <= count($tunes); $i++) { 
	$relations[] = "(1, {$i})";
}
echo implode(',', $relations);
echo ";\n";